In [1]:
import numpy as np

In [2]:
a1=np.array([[2,3,8],[5,4,1],[3,2,5]])
print('First array =\n'+str(a1))
a2=np.array([[2,4,3],[8,5,2],[9,4,3]])
print('Second array =\n'+str(a2))
a3=[5,9,2,3,4,1,7,3,5,7,6.4]

First array =
[[2 3 8]
 [5 4 1]
 [3 2 5]]
Second array =
[[2 4 3]
 [8 5 2]
 [9 4 3]]


In [3]:
add=a1+a2
print('Addition =\n'+str(add))

Addition =
[[ 4  7 11]
 [13  9  3]
 [12  6  8]]


In [4]:
mul=a1*a2
print('Multiplpication =\n'+str(mul))

Multiplpication =
[[ 4 12 24]
 [40 20  2]
 [27  8 15]]


In [5]:
mat_mul=a1.dot(a2)
print('Matrix Multiplication =\n'+str(mat_mul))

Matrix Multiplication =
[[100  55  36]
 [ 51  44  26]
 [ 67  42  28]]


In [11]:
print('\n Input string =\t')
print(a3)
a3.sort()
print('\n Sorted string =\t')
print(a3)
a3.sort(reverse=True)
print('\n Reverse Sorted string =\t')
print(a3)


 Input string =	
[9, 7, 7, 6.4, 5, 5, 4, 3, 3, 2, 1]

 Sorted string =	
[1, 2, 3, 3, 4, 5, 5, 6.4, 7, 7, 9]

 Reverse Sorted string =	
[9, 7, 7, 6.4, 5, 5, 4, 3, 3, 2, 1]
